version: "3.8"
services:

#  mysql8:
#    image: mysql:8.0.27
#    command: mysqld --default-authentication-plugin=mysql_native_password
#    #    volumes:
#    #      - dbdata:/var/lib/mysql/data
#    environment:
#      MYSQL_DATABASE: 'inventory'
#      MYSQL_USER: 'inventory' # So you don't have to use root, but you can if you like
#      MYSQL_PASSWORD: 'password' # You can use whatever password you like
#      MYSQL_ROOT_PASSWORD: 'password' # Password for root access
#    ports:
#      - "3307:3306" # <Port exposed> : < MySQL Port running inside container>
#    networks:
#      - appnetwork # network to communicate
  db:
    container_name: inventory_management_db
    image: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
#      - MYSQL_DB=inventory_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    networks:
      - appnetwork

  web:
    container_name: inventory_management_web
    build: .
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_NAME=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - appnetwork

networks:
  appnetwork:
    name: application_network