version: "3.8"
services:
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE='inventory_dev'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='1234'
      - MYSQL_ROOT_PASSWORD='1234'
      - MYSQL_HOST=''
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db
