version: "3.8"
services:
  db:
    container_name: inventory_management_db
    image: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_DB=inventory_db
#      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"

  django_gunicorn:
#    command: bash -c "
#      python manage.py makemigrations --no-input
#      && python manage.py migrate --no-input
#      "
    volumes:
      - /static:/static
    env_file:
      - .env
    environment:
      - MYSQL_NAME=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306
    build: .
#      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - /static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
