# Generated by Django 4.0.3 on 2022-05-11 13:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Za-z]+([ ][a-zA-Z]+)*', 'Enter a valid name')])),
                ('description', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('updated_date', models.DateField(default=datetime.date.today)),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organisations.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Za-z]+([ ][a-zA-Z]+)*', 'Enter a valid name')])),
                ('description', models.CharField(max_length=400, null=True)),
                ('available_stock', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('updated_date', models.DateField(default=datetime.date.today)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.category')),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organisations.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
