# Generated by Django 4.0.3 on 2022-03-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_order'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
