# Generated by Django 4.0.3 on 2022-05-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('products', '0002_rename_organisation_id_category_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisation', to='organisations.organisation'),
        ),
    ]
