# Generated by Django 4.0.3 on 2022-03-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sales_order', models.BooleanField(default=True)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('customers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='orders.customer')),
                ('products', models.ManyToManyField(to='products.product')),
                ('vendors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_id', to='orders.vendor')),
            ],
        ),
    ]
