# Generated by Django 4.0.3 on 2022-05-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0001_initial"),
        ("payments", "0001_initial"),
        ("products", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="organisation",
            field=models.ForeignKey(
                db_column="organisation_uid",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="organisations.organisation",
                to_field="organisation_uid",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                db_column="invoice_uid",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="payments.invoice",
                to_field="invoice_uid",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="organisation",
            field=models.ForeignKey(
                db_column="organisation_uid",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="organisations.organisation",
                to_field="organisation_uid",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="vendors",
            field=models.ForeignKey(
                blank=True,
                db_column="vendor_uid",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.vendor",
                to_field="vendor_uid",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                db_column="order_uid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_products",
                to="orders.order",
                to_field="order_uid",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                db_column="product_uid",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="products.product",
                to_field="product_uid",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="organisation",
            field=models.ForeignKey(
                db_column="organisation_uid",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="organisations.organisation",
                to_field="organisation_uid",
            ),
        ),
    ]
