# Generated by Django 4.0.3 on 2022-05-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='organisation_id',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='organisation_id',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='organisation_id',
            new_name='organisation',
        ),
    ]
