# Generated by Django 4.0.3 on 2022-03-30 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
        ('orders', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sales_order', models.BooleanField(default=True)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('customers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.OrderProducts', to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_id', to='orders.vendor'),
        ),
    ]
