# Generated by Django 4.0.3 on 2022-04-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.BigIntegerField(default=100000),
        ),
    ]
