# Generated by Django 4.0.3 on 2022-04-27 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customer_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 5, 12)),
        ),
    ]
