# Generated by Django 4.0.3 on 2022-03-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
        ('orders', '0003_order_orderproducts_order_products_order_vendors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProducts',
            new_name='OrderProduct',
        ),
    ]
