# Generated by Django 4.0.3 on 2022-03-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
        ('orders', '0004_rename_orderproducts_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together={('product', 'order')},
        ),
    ]
