# Generated by Django 4.0.3 on 2022-05-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_customers_remove_order_is_sales_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallet',
        ),
    ]
