# Generated by Django 4.0.3 on 2022-05-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_deleted'),
        ('orders', '0006_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='organisation',
            field=models.ForeignKey(db_column='organisation_uid', on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation', to_field='organisation_uid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organisation',
            field=models.ForeignKey(db_column='organisation_uid', on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation', to_field='organisation_uid'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='organisation',
            field=models.ForeignKey(db_column='organisation_uid', on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation', to_field='organisation_uid'),
        ),
    ]
