# Generated by Django 4.0.3 on 2022-05-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_invoice_organisation_and_more'),
        ('orders', '0007_alter_customer_organisation_alter_order_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(blank=True, db_column='invoice_uid', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payments.invoice', to_field='invoice_uid'),
        ),
    ]
