# Generated by Django 4.0.3 on 2022-04-03 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Za-z]+([ ][a-zA-Z]+)*', 'Enter a valid name')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Za-z]+([ ][a-zA-Z]+)*', 'Enter a valid name')]),
        ),
    ]
