# Generated by Django 4.0.3 on 2022-05-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='wallet',
            field=models.BigIntegerField(default=100000),
        ),
    ]
