# Generated by Django 4.0.3 on 2022-05-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_vendor_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='wallet',
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.BigIntegerField(default=100000),
        ),
    ]
