# Generated by Django 4.0.3 on 2022-04-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_customer_remove_order_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.vendor'),
        ),
    ]
