# Generated by Django 4.0.3 on 2022-04-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.vendor'),
        ),
    ]
