# Generated by Django 4.0.3 on 2022-05-06 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='outstanding_payables',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='outstanding_payables',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 5, 22)),
        ),
    ]
