# Generated by Django 4.0.3 on 2022-06-29 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_staff_remove_user_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
