# Generated by Django 4.0.3 on 2022-06-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
