# Generated by Django 4.0.3 on 2022-05-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_deleted_repairingstock_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
