# Generated by Django 4.0.3 on 2022-05-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
