# Generated by Django 4.0.3 on 2022-05-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="organisation",
            field=models.ForeignKey(
                db_column="organisation_uid",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="organisations.organisation",
                to_field="organisation_uid",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                db_column="invoice_uid",
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.invoice",
                to_field="invoice_uid",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="organisation",
            field=models.ForeignKey(
                db_column="organisation_uid",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="organisations.organisation",
                to_field="organisation_uid",
            ),
        ),
    ]
