# Generated by Django 4.0.3 on 2022-04-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
