# Generated by Django 4.0.3 on 2022-05-11 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_organisation_id_invoice_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_deadline',
            field=models.DateField(default=datetime.date(2022, 5, 27)),
        ),
    ]
