# Generated by Django 4.0.3 on 2022-05-19 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_invoice_organisation_alter_payment_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_deadline",
            field=models.DateField(default=datetime.date(2022, 6, 3)),
        ),
    ]
