# Generated by Django 4.0.3 on 2022-04-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Cheque'), (2, 'Cash'), (3, 'Digital')], default=2),
        ),
    ]
