# Generated by Django 4.0.3 on 2022-04-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_amount_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
