# Generated by Django 4.0.3 on 2022-05-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_deleted'),
        ('payments', '0005_alter_invoice_payment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='organisation',
            field=models.ForeignKey(db_column='organisation_uid', on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation', to_field='organisation_uid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='organisation',
            field=models.ForeignKey(db_column='organisation_uid', on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation', to_field='organisation_uid'),
        ),
    ]
